# Generated by Django 4.2.7 on 2024-06-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimesVisitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(max_length=30, verbose_name='ساعت نوبت دادن')),
            ],
        ),
        migrations.CreateModel(
            name='weeksTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks_time', models.TextField(max_length=10, verbose_name='روزهای هفته')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], verbose_name='تاریخ-روز')),
                ('month', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='تاریخ-ماه')),
                ('year', models.IntegerField(choices=[(1403, 1403), (1404, 1404), (1405, 1405), (1406, 1406), (1407, 1407)], verbose_name='تاریخ سال')),
                ('time', models.ManyToManyField(related_name='times', to='appointment.timesvisitmodel', verbose_name='زمان های ویزیت')),
                ('weeks_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.weekstimemodel', verbose_name='روز هفته')),
            ],
        ),
    ]
