# Generated by Django 4.2.7 on 2024-06-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointmentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentmodel',
            options={'verbose_name': 'نوبت دهی سیگنال\u200cهای مغزی EEG', 'verbose_name_plural': 'نوبت دهی سیگنال\u200cهای مغزی EEG'},
        ),
        migrations.AlterModelOptions(
            name='timesvisitmodel',
            options={'verbose_name': 'ساعت های ویزیت', 'verbose_name_plural': 'ساعت های ویزیت'},
        ),
        migrations.AlterModelOptions(
            name='weekstimemodel',
            options={'verbose_name': 'روز های هفته ', 'verbose_name_plural': 'روز های هفته'},
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
