# Generated by Django 4.2.7 on 2024-06-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointmentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='time',
            field=models.ManyToManyField(blank=True, null=True, related_name='times', to='appointment.timesvisitmodel', verbose_name='زمان های ویزیت'),
        ),
    ]
